<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_Login</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>dd1d3a94-5e30-4f1b-a358-71da565ca592</testSuiteGuid>
   <testCaseLink>
      <guid>eaf74cbb-3030-423c-8836-5aa48f561f35</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Tc1</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7ebce4ba-b464-4d79-b03b-3721170970f3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a9551ab-21ef-4bf0-9cdd-0ec6a7f4d6cd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>72485f31-624a-4c44-8a22-35ad6cdebe08</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cc4a5802-4ff7-4234-9555-5f084802038f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Tc2</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9ec7acc2-76b5-4ad4-9e46-53577995301a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c99b3ae4-122d-406b-bc16-caf37d37fb2a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>47d182f5-eecd-41b2-a50a-8ef50f7bdd74</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f3a7c051-a09e-41e8-aba8-1b64bbd0634a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Tc3</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec4523b7-5348-46e4-9ef7-309975afe98d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f7872489-3870-496b-ae86-6c0ee32bcb06</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e4c944a-354d-48d3-a8b0-71de18875442</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>eb258b0d-2e9b-403f-aa70-b1880644db9b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Tc4</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1a9138dc-2b39-4e3f-bb7d-ff7d1f667f90</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cd7c59bf-de2f-43fc-bcd1-17fe131a9f1f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4a5711ab-b09a-48fa-affa-ce6d6fae99ed</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d0c821f6-897f-4758-a62c-ea479bfeb4fb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Tc5</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>df5724cf-301d-4c46-8e82-1c99325a4dcc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c43249a1-0304-4075-acf8-423e77109f9e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>049b9120-9622-4455-9b3d-06713a7cf5b5</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
