<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_Login</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient>dientq1999@gmail.com;</mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>dd1d3a94-5e30-4f1b-a358-71da565ca592</testSuiteGuid>
   <testCaseLink>
      <guid>df4735e4-0e8e-41bb-986b-97b89fbf4f4a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Tc1</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cba1efb6-1c8b-4226-9d07-0a88e2edbbf1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>69a20ec6-2f05-4ffe-869d-c1a168cfd77e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ced59834-c3ab-42a3-917b-92413b04df99</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3c66c3a5-9697-4f4a-86b0-e800ae2b3b80</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Tc2</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>03ea66de-cfdb-4520-b649-c74a7cbd8393</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d1aecfed-5bde-4016-a4c2-40f9e14a2e31</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f3e37da6-6823-4b33-98c5-c1ba24309980</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8f0baf45-47eb-4dfb-9bfc-55a9cc077442</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Tc3</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d3033e9f-4b95-4a02-8293-69383dd68f7c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1999f564-868c-47bf-a2cb-f4fdb81806c4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e0604651-5dd2-47f9-a1aa-3e9865cc84bd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ad556bc1-cb1a-4d46-9c1d-ea5a78642366</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Tc4</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>20355cd2-6f83-4024-a707-b38a2cafaa6f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>834c4d0a-6111-47cb-9e39-9c91eacd06e9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3f28ce2f-efba-4829-ade6-50e34873c8e4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>85c80b4f-c293-4e44-bcca-f8cbc01da752</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Tc5</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f5d51876-40d1-4d41-b4b6-66f093858592</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f0c9d3c5-cfb3-470c-b9e5-30028fcad879</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8cc58036-21ef-4b02-946b-a269f1d87f7e</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
